# Generated by Django 2.1.2 on 2018-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('avito_ad_number', models.IntegerField(null=True)),
                ('publication_date', models.DateField(null=True)),
                ('publication_time', models.TimeField(null=True)),
                ('photo_link', models.TextField(null=True)),
                ('adress', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
