# Generated by Django 2.0 on 2018-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='deletion_date',
            field=models.DateField(null=True),
        ),
    ]
