# Generated by Django 2.1.2 on 2018-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_deletion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_ad_number', models.IntegerField(null=True)),
                ('five_nearest', models.TextField(null=True)),
            ],
        ),
    ]
