# Generated by Django 2.1.2 on 2018-11-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181103_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomend',
            old_name='id_recommend',
            new_name='five_nearest',
        ),
        migrations.RemoveField(
            model_name='recomend',
            name='weight',
        ),
    ]
