# Generated by Django 2.1.2 on 2018-11-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20181105_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='recomendation_list',
            new_name='recommendation_list',
        ),
    ]
